### ISSUE TITLE
Is it possible to write an RDF triple using YAML list?

### ISSUE THREAD

**Issue by anatoly-scherbakov** [octadocs/vocabulari.es#24]
For example:

```yaml
rules:
  - name: "Every triple implies types for its parts"
    given: [_:subject, _:predicate, _:object]
    implies:
      - [_:subject, rdf:type, rdfs:Resource]
      - [_:predicate, rdf:type, rdf:Property]
      - [_:object, rdf:type, rdfs:Resource]
```
